mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: disabled  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: -1 # 逻辑未删除值(默认为 0)
      # 配置slq打印日志
      #configuration:
       # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

